package GameApp;


/**
* GameApp/GameCallbackPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Terça-feira, 27 de Junho de 2017 10h08min48s BRT
*/

public abstract class GameCallbackPOA extends org.omg.PortableServer.Servant
 implements GameApp.GameCallbackOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("callback", new java.lang.Integer (0));
    _methods.put ("askNumberSticksInHand", new java.lang.Integer (1));
    _methods.put ("chooseABet", new java.lang.Integer (2));
    _methods.put ("getAvailableSticks", new java.lang.Integer (3));
    _methods.put ("getSticksInHand", new java.lang.Integer (4));
    _methods.put ("checkRoundResult", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GameApp/GameCallback/callback
       {
         String message = in.read_string ();
         this.callback (message);
         out = $rh.createReply();
         break;
       }

       case 1:  // GameApp/GameCallback/askNumberSticksInHand
       {
         float $result = (float)0;
         $result = this.askNumberSticksInHand ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // GameApp/GameCallback/chooseABet
       {
         float maxValue = in.read_float ();
         float $result = (float)0;
         $result = this.chooseABet (maxValue);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // GameApp/GameCallback/getAvailableSticks
       {
         float $result = (float)0;
         $result = this.getAvailableSticks ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // GameApp/GameCallback/getSticksInHand
       {
         float $result = (float)0;
         $result = this.getSticksInHand ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 5:  // GameApp/GameCallback/checkRoundResult
       {
         float numberSticks = in.read_float ();
         boolean $result = false;
         $result = this.checkRoundResult (numberSticks);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameApp/GameCallback:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameCallback _this() 
  {
    return GameCallbackHelper.narrow(
    super._this_object());
  }

  public GameCallback _this(org.omg.CORBA.ORB orb) 
  {
    return GameCallbackHelper.narrow(
    super._this_object(orb));
  }


} // class GameCallbackPOA
