package GameApp;


/**
* GameApp/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Terça-feira, 27 de Junho de 2017 10h08min48s BRT
*/

public interface GameOperations 
{
  String say (GameApp.GameCallback objref, String message);
  void connectNewPlayer (GameApp.GameCallback callbackObj);
} // interface GameOperations
