package GameApp;

/**
* GameApp/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Terça-feira, 27 de Junho de 2017 10h08min48s BRT
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (GameApp.Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.GameHelper.type ();
  }

}
