package GameApp;


/**
* GameApp/GameCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Terça-feira, 27 de Junho de 2017 10h08min48s BRT
*/

public interface GameCallbackOperations 
{
  void callback (String message);
  float askNumberSticksInHand ();
  float chooseABet (float maxValue);
  float getAvailableSticks ();
  float getSticksInHand ();
  boolean checkRoundResult (float numberSticks);
} // interface GameCallbackOperations
