package GameApp;

/**
* GameApp/GameCallbackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Terça-feira, 27 de Junho de 2017 10h08min48s BRT
*/

public final class GameCallbackHolder implements org.omg.CORBA.portable.Streamable
{
  public GameApp.GameCallback value = null;

  public GameCallbackHolder ()
  {
  }

  public GameCallbackHolder (GameApp.GameCallback initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameApp.GameCallbackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameApp.GameCallbackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameApp.GameCallbackHelper.type ();
  }

}
