package GameApp;


/**
* GameApp/GameCallbackHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corba.idl
* Terça-feira, 27 de Junho de 2017 10h08min48s BRT
*/

abstract public class GameCallbackHelper
{
  private static String  _id = "IDL:GameApp/GameCallback:1.0";

  public static void insert (org.omg.CORBA.Any a, GameApp.GameCallback that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameApp.GameCallback extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameApp.GameCallbackHelper.id (), "GameCallback");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameApp.GameCallback read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameCallbackStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameApp.GameCallback value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameApp.GameCallback narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameApp.GameCallback)
      return (GameApp.GameCallback)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameApp._GameCallbackStub stub = new GameApp._GameCallbackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameApp.GameCallback unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameApp.GameCallback)
      return (GameApp.GameCallback)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameApp._GameCallbackStub stub = new GameApp._GameCallbackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
